#!/usr/bin/env python3
"""Interactive camera tuner for the libcamera softISP + v4l2-relayd stack.

Run:  sudo python3 tuner.py    then open http://127.0.0.1:8787

Writes /usr/share/libcamera/ipa/simple/ov08x40.yaml (CCM from the
saturation + RGB gain sliders) and /etc/v4l2-relayd.d/camera.conf
(gst post-processing from brightness/contrast/gamma sliders), restarts
v4l2-relayd@camera, and shows a live 30fps preview.

NOTE: the virtual camera only supports ONE reader at a time. While this
tuner runs, other apps (Meet, Zoom...) cannot use the camera. Ctrl-C the
tuner when you're done, then join your call.
"""
import http.server
import json
import os
import subprocess
import threading
import time

PORT = 8787


def find_device(label="Virtual Camera"):
    import glob
    for n in glob.glob("/sys/devices/virtual/video4linux/*/name"):
        try:
            with open(n) as fh:
                if fh.read().strip() == label:
                    return "/dev/" + n.split("/")[-2]
        except OSError:
            pass
    raise SystemExit("no v4l2loopback device labelled 'Virtual Camera' - "
                     "run setup-relay.sh first")


DEVICE = find_device()
YAML_PATH = "/usr/share/libcamera/ipa/simple/ov08x40.yaml"
CONF_PATH = "/etc/v4l2-relayd.d/camera.conf"
STATE_PATH = "/etc/v4l2-relayd.d/tuner-state.json"
SERVICE = "v4l2-relayd@camera.service"

DEFAULTS = {
    "saturation": 1.35,
    "gain_r": 1.03,
    "gain_g": 0.93,
    "gain_b": 1.03,
    "brightness": 0.0,
    "contrast": 1.0,
    "gamma": 1.0,
    "hflip": 0.0,
    "agc_target": 2.5,
}

LUMA = (0.2126, 0.7152, 0.0722)

state_lock = threading.Lock()


def compute_ccm(sat, gr, gg, gb):
    rows = []
    for i, gain in enumerate((gr, gg, gb)):
        row = [((1 - sat) * LUMA[j] + (sat if i == j else 0)) * gain
               for j in range(3)]
        rows.append(row)
    return rows


def yaml_text(p):
    m = compute_ccm(p["saturation"], p["gain_r"], p["gain_g"], p["gain_b"])
    f = [f"{v:.4f}" for row in m for v in row]
    ccm = (f"[ {f[0]}, {f[1]}, {f[2]},\n"
           f"                {f[3]}, {f[4]}, {f[5]},\n"
           f"                {f[6]}, {f[7]}, {f[8]} ]")
    return f"""# SPDX-License-Identifier: CC0-1.0
# Generated by cvs-dep-clear tuner.py - hand calibration, not factory data
%YAML 1.1
---
version: 1
algorithms:
  - BlackLevel:
  - Awb:
  - Ccm:
      ccms:
        - ct: 2860
          ccm: {ccm}
        - ct: 6500
          ccm: {ccm}
  - Adjust:
  - Agc:
...
"""


def conf_text(p):
    post = ""
    if p["hflip"]:
        post += " ! videoflip method=horizontal-flip"
    if p["brightness"] != 0 or p["contrast"] != 1:
        post += (f" ! videobalance brightness={p['brightness']:.2f}"
                 f" contrast={p['contrast']:.2f}")
    if p["gamma"] != 1:
        post += f" ! gamma gamma={p['gamma']:.2f}"
    return ('VIDEOSRC="libcamerasrc ! '
            "video/x-raw,format=RGBA,width=1280,height=720,framerate=30/1"
            f"{post} ! videoconvert\"\n"
            # read by the (optionally patched) softISP AGC; harmless otherwise
            f"SOFTISP_AGC_TARGET={p['agc_target']:.2f}\n")


def load_state():
    try:
        with open(STATE_PATH) as fh:
            saved = json.load(fh)
        return {**DEFAULTS, **{k: saved[k] for k in DEFAULTS if k in saved}}
    except Exception:
        return dict(DEFAULTS)


def apply_state(p):
    with open(YAML_PATH, "w") as fh:
        fh.write(yaml_text(p))
    with open(CONF_PATH, "w") as fh:
        fh.write(conf_text(p))
    with open(STATE_PATH, "w") as fh:
        json.dump(p, fh, indent=2)
    subprocess.run(["systemctl", "restart", SERVICE], check=True, timeout=30)


class Capture(threading.Thread):
    """THE single reader of the virtual camera (the loopback allows only
    one). Parses the JPEG stream and fans frames out to all HTTP clients."""

    def __init__(self):
        super().__init__(daemon=True)
        self.cond = threading.Condition()
        self.frame = None
        self.seq = 0
        self.proc = None
        self.stop_flag = False

    def run(self):
        soi = b"\xff\xd8\xff"
        while not self.stop_flag:
            self.proc = subprocess.Popen(
                ["gst-launch-1.0", "-q",
                 "v4l2src", f"device={DEVICE}", "!",
                 "videoconvert", "!", "jpegenc", "quality=80", "!",
                 "fdsink"],
                stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
            buf = b""
            while True:
                chunk = self.proc.stdout.read(65536)
                if not chunk:
                    break  # died (relay restart / warm-up race): respawn
                buf += chunk
                while True:
                    first = buf.find(soi)
                    nxt = buf.find(soi, first + 3) if first >= 0 else -1
                    if nxt < 0:
                        if first > 0:
                            buf = buf[first:]
                        break
                    frame, buf = buf[first:nxt], buf[nxt:]
                    with self.cond:
                        self.frame = frame
                        self.seq += 1
                        self.cond.notify_all()
            self.proc.kill()
            if not self.stop_flag:
                time.sleep(1.0)

    def bounce(self):
        if self.proc and self.proc.poll() is None:
            self.proc.kill()

    def wait_frame(self, last_seq, timeout=5.0):
        with self.cond:
            self.cond.wait_for(lambda: self.seq != last_seq, timeout=timeout)
            return self.frame, self.seq


capture = Capture()

PAGE = """<!doctype html><html><head><meta charset="utf-8">
<title>Camera Tuner</title><style>
body{font-family:system-ui;background:#111;color:#ddd;margin:0;display:flex;gap:24px;padding:24px;flex-wrap:wrap}
#panel{min-width:340px;max-width:420px}
h1{font-size:18px;margin:0 0 12px}
.row{margin:10px 0}
label{display:flex;justify-content:space-between;font-size:13px;margin-bottom:2px}
input[type=range]{width:100%}
img{max-width:840px;width:100%;border-radius:8px;background:#000;min-height:200px}
#status{font-size:12px;color:#8c8;min-height:16px;margin:8px 0}
button{background:#2563eb;border:0;color:#fff;padding:8px 14px;border-radius:6px;margin-right:8px;cursor:pointer}
button.sec{background:#444}
pre{background:#1c1c1c;padding:10px;border-radius:6px;font-size:11px;overflow-x:auto}
small{color:#888}
.warn{color:#fbbf24;font-size:12px;display:block;margin-top:8px}</style></head><body>
<div id="panel"><h1>ThinkPad camera tuner</h1>
<div id="sliders"></div>
<div id="status"></div>
<button onclick="apply()">Apply</button>
<button class="sec" onclick="resetAll()">Reset defaults</button>
<label style="margin-top:10px"><span>Auto-apply on release</span>
<input type="checkbox" id="auto" checked style="width:auto"></label>
<span class="warn">While the tuner runs it owns the camera - Meet/Zoom
can't use it. Ctrl-C the tuner in the terminal when done, then join
your call with the tuned settings.</span>
<h1 style="margin-top:16px">Current settings</h1><pre id="dump"></pre></div>
<div style="flex:1;min-width:400px"><h1>Live preview (30 fps)</h1>
<img id="pv" src="/stream"><br>
<small id="pverr"></small></div>
<script>
const SLIDERS = [
 ["saturation","Saturation",0.8,2.2,0.05],
 ["gain_r","Red gain (higher = warmer)",0.85,1.2,0.01],
 ["gain_g","Green gain (lower = less green)",0.75,1.15,0.01],
 ["gain_b","Blue gain (higher = cooler)",0.85,1.2,0.01],
 ["brightness","Brightness (post)",-0.4,0.4,0.02],
 ["contrast","Contrast (post)",0.5,1.8,0.05],
 ["gamma","Gamma (post, <1 darkens mids)",0.4,2.5,0.05],
 ["agc_target","Exposure target (needs patched IPA)",1.0,3.5,0.1],
];
let state={};
function build(){
 const d=document.getElementById("sliders");
 d.innerHTML="";
 for(const [k,label,min,max,step] of SLIDERS){
  const v=state[k];
  d.insertAdjacentHTML("beforeend",
   `<div class="row"><label><span>${label}</span><b id="v_${k}">${v}</b></label>
    <input type="range" id="s_${k}" min="${min}" max="${max}" step="${step}" value="${v}"
     oninput="document.getElementById('v_${k}').textContent=this.value"
     onchange="state['${k}']=parseFloat(this.value);maybeApply()"></div>`);
 }
 d.insertAdjacentHTML("beforeend",
  `<div class="row"><label><span>Mirror image (horizontal flip)</span>
   <input type="checkbox" id="s_hflip" ${state.hflip?"checked":""} style="width:auto"
    onchange="state.hflip=this.checked?1:0;maybeApply()"></label></div>`);
 document.getElementById("dump").textContent=JSON.stringify(state,null,1);
}
async function load(){state=await (await fetch("/state")).json();build();}
function maybeApply(){if(document.getElementById("auto").checked)apply();}
async function apply(){
 setStatus("applying + restarting relay…");
 const r=await fetch("/apply",{method:"POST",body:JSON.stringify(state)});
 setStatus(r.ok?"applied - preview resumes in a few seconds":"apply FAILED: "+await r.text());
 document.getElementById("dump").textContent=JSON.stringify(state,null,1);
}
function reconnect(){document.getElementById("pv").src="/stream?"+Date.now();}
document.getElementById("pv").onerror=()=>{
 document.getElementById("pverr").textContent="preview reconnecting…";
 setTimeout(reconnect,1500);
};
document.getElementById("pv").onload=()=>{document.getElementById("pverr").textContent=""};
async function resetAll(){
 state=await (await fetch("/reset",{method:"POST"})).json();build();
 setStatus("reset to defaults + applied");
}
function setStatus(t){document.getElementById("status").textContent=t}
load();
</script></body></html>"""


class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def _send(self, code, body, ctype="text/plain"):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body if isinstance(body, bytes) else body.encode())

    def do_GET(self):
        if self.path == "/":
            self._send(200, PAGE, "text/html")
        elif self.path.startswith("/preview.jpg"):
            frame, _ = capture.wait_frame(-1, timeout=3)
            if frame:
                self._send(200, frame, "image/jpeg")
            else:
                self._send(404, "no frame yet")
        elif self.path.startswith("/stream"):
            self.mjpeg_stream()
        elif self.path == "/state":
            self._send(200, json.dumps(load_state()), "application/json")
        else:
            self._send(404, "not found")

    def mjpeg_stream(self):
        """Serve frames from the single shared Capture thread."""
        boundary = "tunerframe"
        self.send_response(200)
        self.send_header("Content-Type",
                         f"multipart/x-mixed-replace;boundary={boundary}")
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        seq = -1
        try:
            while True:
                frame, seq = capture.wait_frame(seq)
                if frame is None:
                    continue  # capture warming up; keep the client waiting
                self.wfile.write(
                    f"--{boundary}\r\n"
                    f"Content-Type: image/jpeg\r\n"
                    f"Content-Length: {len(frame)}\r\n\r\n".encode()
                    + frame + b"\r\n")
        except (BrokenPipeError, ConnectionResetError):
            pass  # client left

    def do_POST(self):
        if self.path == "/apply":
            n = int(self.headers.get("Content-Length", 0))
            try:
                p = {**DEFAULTS, **json.loads(self.rfile.read(n))}
                p = {k: float(p[k]) for k in DEFAULTS}
            except Exception as e:
                return self._send(400, f"bad request: {e}")
        elif self.path == "/reset":
            p = dict(DEFAULTS)
        else:
            return self._send(404, "not found")
        try:
            with state_lock:
                capture.bounce()  # release the device during the restart
                apply_state(p)
            self._send(200, json.dumps(p), "application/json")
        except Exception as e:
            self._send(500, f"apply failed: {e}")


def main():
    if os.geteuid() != 0:
        raise SystemExit("run with sudo (writes system config + restarts the relay)")
    capture.start()
    srv = http.server.ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    print(f"Camera tuner: http://127.0.0.1:{PORT}")
    print("NOTE: while this runs, other apps cannot use the camera.")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        capture.stop_flag = True
        capture.bounce()


if __name__ == "__main__":
    main()
